# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/itai_a417/20465_Reloaded/mReloaded14

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/itai_a417/20465_Reloaded/mReloaded14

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itai_a417/20465_Reloaded/mReloaded14/CMakeFiles /home/itai_a417/20465_Reloaded/mReloaded14//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itai_a417/20465_Reloaded/mReloaded14/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mReloaded14

# Build rule for target.
mReloaded14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mReloaded14
.PHONY : mReloaded14

# fast build rule for target.
mReloaded14/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/build
.PHONY : mReloaded14/fast

src/assembler.o: src/assembler.c.o
.PHONY : src/assembler.o

# target to build an object file
src/assembler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/assembler.c.o
.PHONY : src/assembler.c.o

src/assembler.i: src/assembler.c.i
.PHONY : src/assembler.i

# target to preprocess a source file
src/assembler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/assembler.c.i
.PHONY : src/assembler.c.i

src/assembler.s: src/assembler.c.s
.PHONY : src/assembler.s

# target to generate assembly for a file
src/assembler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/assembler.c.s
.PHONY : src/assembler.c.s

src/first_pass.o: src/first_pass.c.o
.PHONY : src/first_pass.o

# target to build an object file
src/first_pass.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/first_pass.c.o
.PHONY : src/first_pass.c.o

src/first_pass.i: src/first_pass.c.i
.PHONY : src/first_pass.i

# target to preprocess a source file
src/first_pass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/first_pass.c.i
.PHONY : src/first_pass.c.i

src/first_pass.s: src/first_pass.c.s
.PHONY : src/first_pass.s

# target to generate assembly for a file
src/first_pass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/first_pass.c.s
.PHONY : src/first_pass.c.s

src/macro.o: src/macro.c.o
.PHONY : src/macro.o

# target to build an object file
src/macro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro.c.o
.PHONY : src/macro.c.o

src/macro.i: src/macro.c.i
.PHONY : src/macro.i

# target to preprocess a source file
src/macro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro.c.i
.PHONY : src/macro.c.i

src/macro.s: src/macro.c.s
.PHONY : src/macro.s

# target to generate assembly for a file
src/macro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro.c.s
.PHONY : src/macro.c.s

src/macro_list.o: src/macro_list.c.o
.PHONY : src/macro_list.o

# target to build an object file
src/macro_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro_list.c.o
.PHONY : src/macro_list.c.o

src/macro_list.i: src/macro_list.c.i
.PHONY : src/macro_list.i

# target to preprocess a source file
src/macro_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro_list.c.i
.PHONY : src/macro_list.c.i

src/macro_list.s: src/macro_list.c.s
.PHONY : src/macro_list.s

# target to generate assembly for a file
src/macro_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/macro_list.c.s
.PHONY : src/macro_list.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/second_pass.o: src/second_pass.c.o
.PHONY : src/second_pass.o

# target to build an object file
src/second_pass.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/second_pass.c.o
.PHONY : src/second_pass.c.o

src/second_pass.i: src/second_pass.c.i
.PHONY : src/second_pass.i

# target to preprocess a source file
src/second_pass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/second_pass.c.i
.PHONY : src/second_pass.c.i

src/second_pass.s: src/second_pass.c.s
.PHONY : src/second_pass.s

# target to generate assembly for a file
src/second_pass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/second_pass.c.s
.PHONY : src/second_pass.c.s

src/symbols.o: src/symbols.c.o
.PHONY : src/symbols.o

# target to build an object file
src/symbols.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/symbols.c.o
.PHONY : src/symbols.c.o

src/symbols.i: src/symbols.c.i
.PHONY : src/symbols.i

# target to preprocess a source file
src/symbols.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/symbols.c.i
.PHONY : src/symbols.c.i

src/symbols.s: src/symbols.c.s
.PHONY : src/symbols.s

# target to generate assembly for a file
src/symbols.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/symbols.c.s
.PHONY : src/symbols.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mReloaded14.dir/build.make CMakeFiles/mReloaded14.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mReloaded14"
	@echo "... src/assembler.o"
	@echo "... src/assembler.i"
	@echo "... src/assembler.s"
	@echo "... src/first_pass.o"
	@echo "... src/first_pass.i"
	@echo "... src/first_pass.s"
	@echo "... src/macro.o"
	@echo "... src/macro.i"
	@echo "... src/macro.s"
	@echo "... src/macro_list.o"
	@echo "... src/macro_list.i"
	@echo "... src/macro_list.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/second_pass.o"
	@echo "... src/second_pass.i"
	@echo "... src/second_pass.s"
	@echo "... src/symbols.o"
	@echo "... src/symbols.i"
	@echo "... src/symbols.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

